### PR TITLE
fix: install missing language pack for GraalVM

### LINKED ISSUE #2487: MOTD colors displaying incorrectly on GraalVM
### Describe the problem

The MOTD of my server displays incorrectly: Instead of the color codes entered as environment variables the motd contains two unknown characters instead of the color formatting sign:

image

I tried all of the below versions:
```
"welcome to &athis server&r!&r\nwe are playing &bVanilla Minecraft &d1.20.2"
"welcome to §athis server§r!§r\nwe are playing §bVanilla Minecraft §d1.20.2"
"welcome to \u00a7athis server\u00a7r!\u00a7r\nwe are playing \u00a7bVanilla Minecraft \u00a7d1.20.2"
# even the simplest with and without quotes
A §l§cMinecraft§r §nserver
```

### Container definition

```yaml
services:
  server:
    restart: always
    image: itzg/minecraft-server:java17-graalvm
    depends_on:
      - db
    env_file: stack.env
    environment:
      UID: 1001
      GID: 1001

      TYPE: PURPUR
      PURPUR_BUILD: LATEST
      REMOVE_OLD_MODS: true

      MEMORY: 2G
      USE_AIKAR_FLAGS: true

      MOTD: A §l§cMinecraft§r §nserver
      #MOTD: "A §l§cMinecraft§r §nserver"
      #MOTD: "welcome to &athis server&r!&r\nwe are playing &bVanilla Minecraft &d1.20.2"
      #MOTD: "welcome to §athis server§r!§r\nwe are playing §bVanilla Minecraft §d1.20.2"
      #MOTD: "welcome to \u00a7athis server\u00a7r!\u00a7r\nwe are playing \u00a7bVanilla Minecraft \u00a7d1.20.2"
      DIFFICULTY: normal
      SPAWN_PROTECTION: 0
      MODE: survival
      ENABLE_QUERY: true
      QUERY_PORT: 25565
      MAX_PLAYERS: 20
      OPS: |-
        player1
      EXISTING_OPS_FILE: SYNCHRONIZE
      WHITELIST: |-
        player1
        player2
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      ENFORCE_WHITELIST: true
      ICON: <my icon>
      OVERRIDE_ICON: true
      TZ: <my timezone>
      ENABLE_ROLLING_LOGS: true
      USE_SIMD_FLAGS: true

      EULA: true
    stop_grace_period: 2m
    ports:
      - 25562:25565/tcp # Server Port
      - 25562:25565/udp # Query Port
    volumes:
      - /data/minecraft/data:/data
      - /data/minecraft/plugins:/plugins:ro
# rest omitted
```

### Container logs

```
[init] Changing uid of minecraft to 1001
[init] Changing gid of minecraft to 1001
[init] Running as uid=1001 gid=1001 with /data as 'drwxr-xr-x 13 1001 1001 4096 Nov 13 00:28 /data'
[init] Resolving type given PURPUR
[mc-image-helper] 00:31:05.825 INFO  : Resolved Purpur version 1.20.2 build 2090
[mc-image-helper] 00:31:05.858 INFO  : The file /data/purpur-1.20.2-2090.jar is already up to date
[init] Removing old mods including:*.jar,*-version.json excluding:
[init] Copying any plugins from /plugins to /data/plugins
[mc-image-helper] 00:31:09.077 INFO  : Copying /plugins/BlueMap-3.17-paper.jar -> /data/plugins/BlueMap-3.17-paper.jar
[mc-image-helper] 00:31:09.085 INFO  : Copying /plugins/Vault.1.7.3.jar -> /data/plugins/Vault.1.7.3.jar
[mc-image-helper] 00:31:09.086 INFO  : Copying /plugins/CoreProtect-22.2.jar -> /data/plugins/CoreProtect-22.2.jar
[mc-image-helper] 00:31:09.087 INFO  : Copying /plugins/EssentialsXChat-2.20.1.jar -> /data/plugins/EssentialsXChat-2.20.1.jar
[mc-image-helper] 00:31:09.088 INFO  : Interpolating /plugins/EssentialsDiscord/config.yml -> /data/plugins/EssentialsDiscord/config.yml
[mc-image-helper] 00:31:09.094 INFO  : Copying /plugins/EssentialsXDiscordLink-2.20.1.jar -> /data/plugins/EssentialsXDiscordLink-2.20.1.jar
[mc-image-helper] 00:31:09.095 INFO  : Copying /plugins/InteractionVisualizer-1.18.7.0.jar -> /data/plugins/InteractionVisualizer-1.18.7.0.jar
[mc-image-helper] 00:31:09.099 INFO  : Interpolating /plugins/LuckPerms/config.yml -> /data/plugins/LuckPerms/config.yml
[mc-image-helper] 00:31:09.103 INFO  : Copying /plugins/EssentialsX-2.20.1.jar -> /data/plugins/EssentialsX-2.20.1.jar
[mc-image-helper] 00:31:09.106 INFO  : Copying /plugins/TAB v4.0.9.jar -> /data/plugins/TAB v4.0.9.jar
[mc-image-helper] 00:31:09.107 INFO  : Copying /plugins/EssentialsXDiscord-2.20.1.jar -> /data/plugins/EssentialsXDiscord-2.20.1.jar
[mc-image-helper] 00:31:09.112 INFO  : Copying /plugins/LuckPerms-Bukkit-5.4.106.jar -> /data/plugins/LuckPerms-Bukkit-5.4.106.jar
[init] Enabling whitelist functionality
[init] Setting mode
[mc-image-helper] 00:31:12.805 INFO  : Created/updated 2 properties in /data/server.properties
[init] Using server icon from <my icon>...
[init] log4j2.xml already created, skipping
[init] Using Aikar's flags
[init] Setting initial memory to 2G and max to 2G
[init] Starting the Minecraft server...
```

### PR DESCRIPTION
**Pull request by Sculas**
Fixes #2487 (followup of https://github.com/itzg/docker-minecraft-server/issues/2487#issuecomment-2539872385). Also sets `LC_ALL` to `en_US.UTF-8`.

### CODE REVIEW

File: build/ol/install-packages.sh [hunk 1]
```diff
@@ -53,6 +53,9 @@ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.s
 dnf update -y
 dnf install -y git-lfs
 
+# Install missing language pack for en_US.UTF-8 (see issue #2487)
+dnf install -y glibc-langpack-en
```
Comment (itzg) [inline build/ol/install-packages.sh:57]: Can you add this to the install that starts on line 27?

File: Dockerfile [hunk 2]
```diff
@@ -64,7 +64,7 @@ WORKDIR /data
 STOPSIGNAL SIGTERM
 
 # End user MUST set EULA and change RCON_PASSWORD
-ENV TYPE=VANILLA VERSION=LATEST EULA="" UID=1000 GID=1000
+ENV TYPE=VANILLA VERSION=LATEST EULA="" UID=1000 GID=1000 LC_ALL=en_US.UTF-8
```
Comment (itzg) [inline Dockerfile:67]: Have you tested this locale setting with the Ubuntu and Alpine based image builds?

**Review by itzg — COMMENTED** [review]
Great research and discovery. Thanks. 

Just a tiny tweak is needed.

**Comment by itzg** [comment]
PR tests pass, so other base distros seem to be fine with it.

File: Dockerfile (hunk 2 above)
Comment (Sculas) [reply Dockerfile:67]: I have not been able to test this yet for the other distros. But since the tests pass as you said, it should be fine.

File: build/ol/install-packages.sh (hunk 1 above)
Comment (Sculas) [reply build/ol/install-packages.sh]: Done in d8fe21f489b2b9a3b2b07ed8257f9dfac9cc224f.

**Review by itzg — APPROVED** [review]

**Comment by itzg** [comment]
Included in this build 

https://github.com/itzg/docker-minecraft-server/actions/runs/12333206137
